name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Info
      run: |
        env | sort

    - name: Build container
      run: |
        sed "s/REPLACE_THIS_WITH_YOUR_ID/`id -u`/" docker-compose.override.yml.example > docker-compose.override.yml
        docker-compose build

    - name: Validate
      run: |
        docker-compose run --rm obs-docu daps -d DC-obs-all validate

    - name: Generate HTML
      run: |
        docker-compose run --rm obs-docu daps -vv -d DC-obs-all html

    - uses: actions/upload-artifact@v2
      with:
        name: obs-docu-html
        path: build/obs-all/html/obs-all/
